---
name: Static deployment
on:
  push:
    branches:
      - main
    path:
      - 'site/**'
env:
  REGISTRY: docker.io

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
      image_tag: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout SERVICE repo
        uses: actions/checkout@v3
        id: checkout_repo
        with:
          ref: ${{ inputs.BRANCH }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: actions/setup-node@v3
        with:
          node-version: 14.21.3

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Prepare hexo
        working-directory: site
        run: |
          pwd;
          rm -rf node_modules && npm install --force
          npm install -g hexo-cli;

      - name: Generate statics files
        working-directory: site
        run: |
          hexo clean;
          hexo generate

      - name: Save build number
        id: build-number-save
        run: echo ${{ steps.vars.outputs.sha_short }} > buildimage.txt

      - name: Publish statics
        id: publish-statics
        uses: actions/upload-artifact@v3
        with:
          name: website-statics
          path: site/public

  deploy:
    name: build statics
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout SERVICE repo
        uses: actions/checkout@v3
        id: checkout_repo
        with:
          ref: ${{ inputs.BRANCH }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            website-statics
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Login to nexus
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: website-statics
          path: artifacts

      - name: Build, tag and push container
        id: build-push-image
        run: |
          docker build . -t psyskeletor/${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
          docker push psyskeletor/${{ env.DOCKER_METADATA_OUTPUT_TAGS }}

      - name: Render image version
        run: |
          sed -i "s/RENDER/${{ env.DOCKER_METADATA_OUTPUT_TAGS }}/g" k8s/deployment.yml

      - name: Push rendered file to remote repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'k8s/'
          destination_repo: 'NicolasTobias/arenero'
          destination_folder: 'website-rl5'
          user_email: 'bender@leveL5.dev'
          user_name: 'Bender'
          commit_message: 'Bender says: ${{ github.event.head_commit.message }}'
